var szmtr = {};
szmtr.lineNumber = 9;
szmtr.width = 5850;
szmtr.height = 5709;
szmtr.line = new Array();
//szmtr.line[5] = {
//  id: 1,
//  name: "1号线",
//  color: "#00b050",
//  maskColor: "#d9f7d9",
//  x1: 364,
//  y1: 2579,
//  x2: 5380,
//  y2: 2320,
//  w: 210
//};
//szmtr.line[6] = {
//  id: 2,
//  name: "2号线",
//  color: "#ff0000",
//  maskColor: "#f5d5d5",
//  x1: 2853,
//  y1: 52,
//  x2: 5615,
//  y2: 3560,
//  w: 210
//};
szmtr.line[0] = {
    id: 3,
    name: "2号线",
    color: "#34b7c3",
    maskColor: "#a8e8ee",
    x1: 1040,
    y1: 920,
	x2: 4748,
    y2: 2905,
    w: 210
};
//szmtr.line[7] = {
//  id: 4,
//  name: "4号线主线",
//  color: "#cbc6c4",
//  maskColor: "#cbc6c4",
//  x1: 2360,
//  y1: 205,
//  x2: 3940,
//  y2: 5214,
//  w: 330
//};
//szmtr.line[1] = {
//  id: 5,
//  name: "4号线支线",
//  color: "#00b0f0",
//  maskColor: "#d3e4f1",
//  x1: 581 * 0,
//  y1: 855,
//  x2: 638,
//  y2: 4175,
//  w: 330
//};
//szmtr.line[1] = {
//  id: 6,
//  name: "5号线",
//  color: "red",
//  maskColor: "#F2F2F2",
//  x1: 300 * 0,
//  y1: 2900,
//  x2: 5235 * 0,
//  y2: 1300,
//  w: 210
//};
//szmtr.line[2] = {
//  id: 7,
//  name: "6号线",
//  color: "#DDDDDD",
//  maskColor: "#F2F2F2",
//  x1: 1200 * 0,
//  y1: 900,
//  x2: 5450 * 0,
//  y2: 3430,
//  w: 210
//};
//szmtr.line[3] = {
//  id: 8,
//  name: "7号线",
//  color: "#DDDDDD",
//  maskColor: "#F2F2F2",
//  x1: 2570 * 0,
//  y1: 470,
//  x2: 0,
//  y2: 0,
//  w: 210
//};
//szmtr.line[4] = {
//  id: 9,
//  name: "8号线",
//  color: "#DDDDDD",
//  maskColor: "#F2F2F2",
//  x1: 1258 * 0,
//  y1: 2150,
//  x2: 4795 * 0,
//  y2: 4010,
//  w: 210
//};
//szmtr.line[5].station = new Array(
//  {
//      id: "0140",
//      name: "木渎",
//      eName: "Mudu",
//      x: 684,
//      y: 2629,
//      tx: 634,
//      ty: 2539,
//      dx: 5,
//      direction1: "钟南街",
//      startTime1: "6:10",
//      endTime1: "22:35",
//      direction2: "木渎",
//      startTime2: "—",
//      endTime2: "—",
//      type: "normal"
//  },
//  {
//      id: "0141",
//      name: "金枫路",
//      eName: "Jinfeng Lu",
//      x: 875,
//      y: 2629,
//      tx: 800,
//      ty: 2719,
//      dx: 0,
//      direction1: "钟南街",
//      startTime1: "6:12",
//      endTime1: "22:37",
//      direction2: "木渎",
//      startTime2: "6:31",
//      endTime2: "23:21",
//      type: "normal"
//  },
//  {
//      id: "0142",
//      name: "汾湖路",
//      eName: "Fenhu Lu",
//      x: 1066,
//      y: 2629,
//      tx: 991,
//      ty: 2539,
//      dx: 15,
//      direction1: "钟南街",
//      startTime1: "6:14",
//      endTime1: "22:39",
//      direction2: "木渎",
//      startTime2: "6:28",
//      endTime2: "23:19",
//      type: "normal"
//  },
//  {
//      id: "0143",
//      name: "玉山路",
//      eName: "Yushan Lu",
//      x: 1259,
//      y: 2629,
//      tx: 1184,
//      ty: 2719,
//      dx: 5,
//      direction1: "钟南街",
//      startTime1: "6:10",
//      endTime1: "22:41",
//      direction2: "木渎",
//      startTime2: "6:26",
//      endTime2: "23:16",
//      type: "normal"
//  },
//  {id: "t0001", name: "过渡点", x: 1314, y: 2629, r: 45, sweep: 0, type: "temp"},
//  {
//      id: "0144",
//      name: "苏州乐园",
//      eName: "Suzhou Amusement Land",
//      x: 1460,
//      y: 2485,
//      tx: 1460,
//      ty: 2575,
//      dx: -60,
//      direction1: "钟南街",
//      startTime1: "6:12",
//      endTime1: "22:44",
//      direction2: "木渎",
//      startTime2: "6:24",
//      endTime2: "23:14",
//      type: "normal"
//  },
//  {id: "t0002", name: "过渡点", x: 1576, y: 2370, r: 45, sweep: 1, type: "temp"},
//  {
//      id: "0145",
//      name: "塔园路",
//      eName: "Tayuan Lu",
//      x: 1655,
//      y: 2370,
//      tx: 1580,
//      ty: 2280,
//      dx: 5,
//      direction1: "钟南街",
//      startTime1: "6:14",
//      endTime1: "22:46",
//      direction2: "木渎",
//      startTime2: "6:22",
//      endTime2: "23:12",
//      type: "normal"
//  },
//  {
//      id: "0146",
//      name: "滨河路",
//      eName: "Binhe Lu",
//      x: 1872,
//      y: 2370,
//      tx: 1797,
//      ty: 2460,
//      dx: 15,
//      direction1: "钟南街",
//      startTime1: "6:10",
//      endTime1: "22:48",
//      direction2: "木渎",
//      startTime2: "6:20",
//      endTime2: "23:10",
//      type: "normal"
//  },
//  {
//      id: "0147",
//      name: "西环路",
//      eName: "Xihuan Lu",
//      x: 2135,
//      y: 2370,
//      tx: 2060,
//      ty: 2280,
//      dx: 0,
//      direction1: "钟南街",
//      startTime1: "6:12",
//      endTime1: "22:50",
//      direction2: "木渎",
//      startTime2: "6:18",
//      endTime2: "23:08",
//      type: "normal"
//  },
//  {
//      id: "0148",
//      name: "桐泾北路",
//      eName: "Tongjing Beilu",
//      x: 2308,
//      y: 2370,
//      tx: 2200,
//      ty: 2465,
//      dx: -5,
//      direction1: "钟南街",
//      startTime1: "6:14",
//      endTime1: "22:52",
//      direction2: "木渎",
//      startTime2: "6:16",
//      endTime2: "23:06",
//      type: "normal"
//  },
//  {
//      id: "s1_0149",
//      name: "广济南路",
//      eName: "Guangji Nanlu",
//      x: 2525,
//      y: 2370,
//      tx: 2555,
//      ty: 2460,
//      dx: 0,
//      direction1: "钟南街",
//      startTime1: "6:10",
//      endTime1: "22:54",
//      direction2: "木渎",
//      startTime2: "6:14",
//      endTime2: "23:04",
//      type: "transfer"
//  },
//  {
//      id: "0150",
//      name: "养育巷",
//      eName: "Yangyu Xiang",
//      x: 2745,
//      y: 2370,
//      tx: 2670,
//      ty: 2280,
//      dx: -20,
//      direction1: "钟南街",
//      startTime1: "6:12",
//      endTime1: "22:57",
//      direction2: "木渎",
//      startTime2: "6:11",
//      endTime2: "23:01",
//      type: "normal"
//  },
//  {
//      id: "s3_0151",
//      name: " 乐桥 ",
//      eName: "Leqiao",
//      x: 2958,
//      y: 2370,
//      tx: 2988,
//      ty: 2460,
//      dx: 5,
//      direction1: "钟南街",
//      startTime1: "6:14",
//      endTime1: "22:59",
//      direction2: "木渎",
//      startTime2: "6:10",
//      endTime2: "23:00",
//      type: "transfer"
//  },
//  {
//      id: "0152",
//      name: "临顿路",
//      eName: "Lindun Lu",
//      x: 3225,
//      y: 2370,
//      tx: 3150,
//      ty: 2280,
//      dx: 5,
//      direction1: "钟南街",
//      startTime1: "6:16",
//      endTime1: "23:01",
//      direction2: "木渎",
//      startTime2: "6:17",
//      endTime2: "22:58",
//      type: "normal"
//  },
//  {
//      id: "0153",
//      name: "相门",
//      eName: "Xiangmen",
//      x: 3410,
//      y: 2370,
//      tx: 3360,
//      ty: 2470,
//      dx: -20,
//      direction1: "钟南街",
//      startTime1: "6:17",
//      endTime1: "23:02",
//      direction2: "木渎",
//      startTime2: "6:16",
//      endTime2: "22:56",
//      type: "normal"
//  },
//  {
//      id: "0154",
//      name: "东环路",
//      eName: "Donghuan Lu",
//      x: 3593,
//      y: 2370,
//      tx: 3518,
//      ty: 2280,
//      dx: -20,
//      direction1: "钟南街",
//      startTime1: "6:19",
//      endTime1: "23:04",
//      direction2: "木渎",
//      startTime2: "6:13",
//      endTime2: "22:54",
//      type: "normal"
//  },
//  {
//      id: "0155",
//      name: "中央公园",
//      eName: "Central Park",
//      x: 3775,
//      y: 2370,
//      tx: 3675,
//      ty: 2460,
//      dx: 15,
//      direction1: "钟南街",
//      startTime1: "6:22",
//      endTime1: "23:07",
//      direction2: "木渎",
//      startTime2: "6:12",
//      endTime2: "22:52",
//      type: "normal"
//  },
//  {
//      id: "0156",
//      name: "星海广场",
//      eName: "Xinghai Spuare",
//      x: 3959,
//      y: 2370,
//      tx: 3859,
//      ty: 2280,
//      dx: -7,
//      direction1: "钟南街",
//      startTime1: "6:24",
//      endTime1: "23:09",
//      direction2: "木渎",
//      startTime2: "6:10",
//      endTime2: "22:50",
//      type: "normal"
//  },
//  {
//      id: "0157",
//      name: "东方之门",
//      eName: "Dongfangzhimeng",
//      x: 4152,
//      y: 2370,
//      tx: 4052,
//      ty: 2460,
//      dx: -35,
//      direction1: "钟南街",
//      startTime1: "6:26",
//      endTime1: "23:11",
//      direction2: "木渎",
//      startTime2: "6:16",
//      endTime2: "22:48",
//      type: "normal"
//  },
//  {
//      id: "0158",
//      name: "文化博览中心",
//      eName: "Culture & Expo Center",
//      x: 4345,
//      y: 2370,
//      tx: 4195,
//      ty: 2270,
//      dx: -10,
//      direction1: "钟南街",
//      startTime1: "6:29",
//      endTime1: "23:14",
//      direction2: "木渎",
//      startTime2: "6:13",
//      endTime2: "22:44",
//      type: "normal"
//  },
//  {
//      id: "0159",
//      name: "时代广场",
//      eName: "Times Square",
//      x: 4528,
//      y: 2370,
//      tx: 4428,
//      ty: 2460,
//      dx: 10,
//      direction1: "钟南街",
//      startTime1: "6:31",
//      endTime1: "23:16",
//      direction2: "木渎",
//      startTime2: "6:11",
//      endTime2: "22:42",
//      type: "normal"
//  },
//  {
//      id: "0160",
//      name: "星湖街",
//      eName: "Xinghu Jie",
//      x: 4710,
//      y: 2370,
//      tx: 4635,
//      ty: 2280,
//      dx: 5,
//      direction1: "钟南街",
//      startTime1: "6:33",
//      endTime1: "23:18",
//      direction2: "木渎",
//      startTime2: "6:10",
//      endTime2: "22:41",
//      type: "normal"
//  },
//  {
//      id: "0161",
//      name: "南施街",
//      eName: "Nanshi Jie",
//      x: 4894,
//      y: 2370,
//      tx: 4819,
//      ty: 2460,
//      dx: 3,
//      direction1: "钟南街",
//      startTime1: "6:35",
//      endTime1: "23:20",
//      direction2: "木渎",
//      startTime2: "6:14",
//      endTime2: "22:39",
//      type: "normal"
//  },
//  {
//      id: "0162",
//      name: "星塘街",
//      eName: "Xingtang Jie",
//      x: 5085,
//      y: 2370,
//      tx: 5010,
//      ty: 2280,
//      dx: -12,
//      direction1: "钟南街",
//      startTime1: "6:37",
//      endTime1: "23:22",
//      direction2: "木渎",
//      startTime2: "6:12",
//      endTime2: "22:37",
//      type: "normal"
//  },
//  {
//      id: "0163",
//      name: "钟南街",
//      eName: "Zhongnan Jie",
//      x: 5280,
//      y: 2370,
//      tx: 5205,
//      ty: 2280,
//      dx: -15,
//      direction1: "钟南街",
//      startTime1: "—",
//      endTime1: "—",
//      direction2: "木渎",
//      startTime2: "6:10",
//      endTime2: "22:35",
//      type: "normal"
//  }
//);
//szmtr.line[6].station = new Array(
//  {
//      id: "0238",
//      name: "骑河",
//      eName: "Qihe",
//      x: 2958,
//      y: 222,
//      tx: 3018,
//      ty: 232,
//      dx: 0,
//      direction1: "桑田岛",
//      startTime1: "6:00",
//      endTime1: "22:56",
//      direction2: "骑河",
//      startTime2: "—",
//      endTime2: "—",
//      type: "normal"
//  },
//  {
//      id: "0239",
//      name: "富翔路",
//      eName: "Fuxiang Lu",
//      x: 2958,
//      y: 372,
//      tx: 3018,
//      ty: 382,
//      dx: 0,
//      direction1: "桑田岛",
//      startTime1: "6:01",
//      endTime1: "22:57",
//      direction2: "骑河",
//      startTime2: "6:45",
//      endTime2: "23:32",
//      type: "normal"
//  },
//  {
//      id: "0240",
//      name: "高铁苏州北站",
//      eName: "Suzhou North Railway Station",
//      x: 2958,
//      y: 520,
//      tx: 3018,
//      ty: 530,
//      dx: 0,
//      direction1: "桑田岛",
//      startTime1: "6:04",
//      endTime1: "23:00",
//      direction2: "骑河",
//      startTime2: "6:43",
//      endTime2: "23:30",
//      type: "normal"
//  },
//  {
//      id: "0241",
//      name: "大湾",
//      eName: "Dawan",
//      x: 2958,
//      y: 672,
//      tx: 3018,
//      ty: 682,
//      dx: 0,
//      direction1: "桑田岛",
//      startTime1: "6:06",
//      endTime1: "23:02",
//      direction2: "骑河",
//      startTime2: "6:41",
//      endTime2: "23:27",
//      type: "normal"
//  },
//  {
//      id: "0242",
//      name: "富元路",
//      eName: "Fuyuan Lu",
//      x: 2958,
//      y: 822,
//      tx: 3018,
//      ty: 832,
//      dx: 0,
//      direction1: "桑田岛",
//      startTime1: "6:00",
//      endTime1: "23:04",
//      direction2: "骑河",
//      startTime2: "6:38",
//      endTime2: "23:25",
//      type: "normal"
//  },
//  {
//      id: "0243",
//      name: "蠡口",
//      eName: "Likou",
//      x: 2958,
//      y: 972,
//      tx: 3018,
//      ty: 982,
//      dx: 0,
//      direction1: "桑田岛",
//      startTime1: "6:02",
//      endTime1: "23:07",
//      direction2: "骑河",
//      startTime2: "6:36",
//      endTime2: "23:22",
//      type: "normal"
//  },
//  {
//      id: "0244",
//      name: "徐图港",
//      eName: "Xutu Gang",
//      x: 2958,
//      y: 1122,
//      tx: 3018,
//      ty: 1132,
//      dx: 0,
//      direction1: "桑田岛",
//      startTime1: "6:04",
//      endTime1: "23:09",
//      direction2: "骑河",
//      startTime2: "6:33",
//      endTime2: "23:20",
//      type: "normal"
//  },
//  {
//      id: "0245",
//      name: "阳澄湖中路",
//      eName: "Yangchenghu Zhonglu",
//      x: 2958,
//      y: 1282,
//      tx: 3018,
//      ty: 1292,
//      dx: 0,
//      direction1: "桑田岛",
//      startTime1: "6:06",
//      endTime1: "23:11",
//      direction2: "骑河",
//      startTime2: "6:31",
//      endTime2: "23:18",
//      type: "normal"
//  },
//  {
//      id: "0246",
//      name: "陆慕",
//      eName: "Lumu",
//      x: 2958,
//      y: 1422,
//      tx: 3018,
//      ty: 1432,
//      dx: 0,
//      direction1: "桑田岛",
//      startTime1: "6:00",
//      endTime1: "23:14",
//      direction2: "骑河",
//      startTime2: "6:28",
//      endTime2: "23:15",
//      type: "normal"
//  },
//  {
//      id: "0247",
//      name: "平泷路东",
//      eName: "Pinglonglu East",
//      x: 2958,
//      y: 1572,
//      tx: 3018,
//      ty: 1582,
//      dx: 0,
//      direction1: "桑田岛",
//      startTime1: "6:02",
//      endTime1: "23:17",
//      direction2: "骑河",
//      startTime2: "6:26",
//      endTime2: "23:12",
//      type: "normal"
//  },
//  {id: "t0011", name: "过渡点", x: 2958, y: 1641, r: 45, sweep: 1, type: "temp"},
//  {
//      id: "0248",
//      name: "平河路",
//      eName: "Pinghe Lu",
//      x: 2900,
//      y: 1700,
//      tx: 2960,
//      ty: 1710,
//      dx: 0,
//      direction1: "桑田岛",
//      startTime1: "6:04",
//      endTime1: "23:18",
//      direction2: "骑河",
//      startTime2: "6:24",
//      endTime2: "23:11",
//      type: "normal"
//  },
//  {
//      id: "s2_0249",
//      name: " 苏州火车站 ",
//      eName: "Suzhou Railway Station",
//      x: 2744,
//      y: 1858,
//      tx: 2814,
//      ty: 1864,
//      dx: 0,
//      direction1: "桑田岛",
//      startTime1: "6:06",
//      endTime1: "23:21",
//      direction2: "骑河",
//      startTime2: "6:22",
//      endTime2: "23:09",
//      type: "transfer"
//  },
//  {
//      id: "0250",
//      name: "山塘街",
//      eName: "Shantang Jie",
//      x: 2585,
//      y: 2019,
//      tx: 2375,
//      ty: 2005,
//      dx: -35,
//      direction1: "桑田岛",
//      startTime1: "6:09",
//      endTime1: "23:23",
//      direction2: "骑河",
//      startTime2: "6:20",
//      endTime2: "23:06",
//      type: "normal"
//  },
//  {id: "t0012", name: "过渡点", x: 2525, y: 2080, r: 45, sweep: 0, type: "temp"},
//  {
//      id: "0251",
//      name: "石路",
//      eName: "Shi Lu",
//      x: 2525,
//      y: 2215,
//      tx: 2365,
//      ty: 2225,
//      dx: 10,
//      direction1: "桑田岛",
//      startTime1: "6:00",
//      endTime1: "23:25",
//      direction2: "骑河",
//      startTime2: "6:18",
//      endTime2: "23:04",
//      type: "normal"
//  },
//  {
//      id: "s1_0252",
//      name: "广济南路",
//      eName: "Guangji Nanlu",
//      x: 2525,
//      y: 2370,
//      tx: 2555,
//      ty: 2460,
//      dx: 0,
//      direction1: "桑田岛",
//      startTime1: "6:02",
//      endTime1: "23:27",
//      direction2: "骑河",
//      startTime2: "6:16",
//      endTime2: "23:02",
//      type: "transfer"
//  },
//  {
//      id: "0253",
//      name: "三香广场",
//      eName: "Sanxiang Square",
//      x: 2525,
//      y: 2590,
//      tx: 2265,
//      ty: 2600,
//      dx: -40,
//      direction1: "桑田岛",
//      startTime1: "6:03",
//      endTime1: "23:29",
//      direction2: "骑河",
//      startTime2: "6:14",
//      endTime2: "23:00",
//      type: "normal"
//  },
//  {
//      id: "0254",
//      name: "劳动路",
//      eName: "Laodong Lu",
//      x: 2525,
//      y: 2785,
//      tx: 2315,
//      ty: 2795,
//      dx: -20,
//      direction1: "桑田岛",
//      startTime1: "6:05",
//      endTime1: "23:31",
//      direction2: "骑河",
//      startTime2: "6:12",
//      endTime2: "22:59",
//      type: "normal"
//  },
//  {
//      id: "0255",
//      name: "胥江路",
//      eName: "Xujiang Lu",
//      x: 2525,
//      y: 2935,
//      tx: 2315,
//      ty: 2945,
//      dx: 0,
//      direction1: "桑田岛",
//      startTime1: "6:07",
//      endTime1: "22:47",
//      direction2: "骑河",
//      startTime2: "6:10",
//      endTime2: "22:57",
//      type: "normal"
//  },
//  {
//      id: "0256",
//      name: "桐泾公园",
//      eName: "Tongjing Park",
//      x: 2525,
//      y: 3072,
//      tx: 2265,
//      ty: 3082,
//      dx: 0,
//      direction1: "桑田岛",
//      startTime1: "6:08",
//      endTime1: "22:48",
//      direction2: "骑河",
//      startTime2: "6:09",
//      endTime2: "22:55",
//      type: "normal"
//  },
//  {
//      id: "0257",
//      name: "友联",
//      eName: "Youlian",
//      x: 2525,
//      y: 3210,
//      tx: 2365,
//      ty: 3220,
//      dx: -8,
//      direction1: "桑田岛",
//      startTime1: "6:11",
//      endTime1: "22:51",
//      direction2: "骑河",
//      startTime2: "6:06",
//      endTime2: "22:53",
//      type: "normal"
//  },
//  {
//      id: "0258",
//      name: "盘蠡路",
//      eName: "Panli lu",
//      x: 2525,
//      y: 3345,
//      tx: 2585,
//      ty: 3285,
//      dx: 20,
//      direction1: "桑田岛",
//      startTime1: "6:13",
//      endTime1: "22:53",
//      direction2: "骑河",
//      startTime2: "6:04",
//      endTime2: "22:50",
//      type: "normal"
//  },
//  {id: "t0013", name: "过渡点", x: 2525, y: 3610, r: 45, sweep: 0, type: "temp"},
//  {
//      id: "0259",
//      name: "新家桥",
//      eName: "Xinjia Qiao",
//      x: 2708,
//      y: 3610,
//      tx: 2633,
//      ty: 3700,
//      dx: 0,
//      direction1: "桑田岛",
//      startTime1: "6:15",
//      endTime1: "22:55",
//      direction2: "骑河",
//      startTime2: "6:02",
//      endTime2: "22:48",
//      type: "normal"
//  },
//  {
//      id: "s4_0260",
//      name: "石湖东路",
//      eName: "Shihu Donglu",
//      x: 2958,
//      y: 3610,
//      tx: 3008,
//      ty: 3530,
//      dx: 0,
//      direction1: "桑田岛",
//      startTime1: "6:18",
//      endTime1: "22:58",
//      direction2: "骑河",
//      startTime2: "6:00",
//      endTime2: "22:46",
//      type: "transfer"
//  },
//  {
//      id: "0261",
//      name: "宝带桥南",
//      eName: "Baodaiqiao South",
//      x: 3262,
//      y: 3610,
//      tx: 3162,
//      ty: 3700,
//      dx: -30,
//      direction1: "桑田岛",
//      startTime1: "6:20",
//      endTime1: "23:00",
//      direction2: "骑河",
//      startTime2: "6:09",
//      endTime2: "22:43",
//      type: "normal"
//  },
//  {
//      id: "0262",
//      name: "尹中路",
//      eName: "Yinzhong Lu",
//      x: 3515,
//      y: 3610,
//      tx: 3440,
//      ty: 3520,
//      dx: -10,
//      direction1: "桑田岛",
//      startTime1: "6:23",
//      endTime1: "23:03",
//      direction2: "骑河",
//      startTime2: "6:07",
//      endTime2: "22:41",
//      type: "normal"
//  },
//  {
//      id: "0263",
//      name: "郭巷",
//      eName: "Guoxiang",
//      x: 3775,
//      y: 3610,
//      tx: 3725,
//      ty: 3700,
//      dx: -20,
//      direction1: "桑田岛",
//      startTime1: "6:25",
//      endTime1: "23:04",
//      direction2: "骑河",
//      startTime2: "6:05",
//      endTime2: "22:39",
//      type: "normal"
//  },
//  {
//      id: "0264",
//      name: "郭苑路",
//      eName: "Guoyuan Lu",
//      x: 3942,
//      y: 3610,
//      tx: 3867,
//      ty: 3520,
//      dx: -10,
//      direction1: "桑田岛",
//      startTime1: "6:27",
//      endTime1: "23:06",
//      direction2: "骑河",
//      startTime2: "6:03",
//      endTime2: "22:37",
//      type: "normal"
//  },
//  {
//      id: "0265",
//      name: "尹山湖",
//      eName: "Yinshan Hu",
//      x: 4107,
//      y: 3610,
//      tx: 4032,
//      ty: 3700,
//      dx: -5,
//      direction1: "桑田岛",
//      startTime1: "6:29",
//      endTime1: "23:08",
//      direction2: "骑河",
//      startTime2: "6:01",
//      endTime2: "22:35",
//      type: "normal"
//  },
//  {
//      id: "0266",
//      name: "独墅湖南",
//      eName: "Dushuhu South",
//      x: 4308,
//      y: 3610,
//      tx: 4208,
//      ty: 3520,
//      dx: -5,
//      direction1: "桑田岛",
//      startTime1: "6:30",
//      endTime1: "23:10",
//      direction2: "骑河",
//      startTime2: "6:00",
//      endTime2: "22:33",
//      type: "normal"
//  },
//  {
//      id: "0267",
//      name: "独墅湖邻里中心",
//      eName: "Dushuhu Neighborhood Center",
//      x: 4510,
//      y: 3610,
//      tx: 4335,
//      ty: 3700,
//      dx: -50,
//      direction1: "桑田岛",
//      startTime1: "6:33",
//      endTime1: "23:13",
//      direction2: "骑河",
//      startTime2: "6:04",
//      endTime2: "22:30",
//      type: "normal"
//  },
//  {
//      id: "0268",
//      name: "月亮湾",
//      eName: "Moon Bay",
//      x: 4710,
//      y: 3610,
//      tx: 4620,
//      ty: 3535,
//      dx: 3,
//      direction1: "桑田岛",
//      startTime1: "6:35",
//      endTime1: "23:15",
//      direction2: "骑河",
//      startTime2: "6:02",
//      endTime2: "22:28",
//      type: "normal"
//  },
//  {
//      id: "0269",
//      name: "松涛街",
//      eName: "Songtao Jie",
//      x: 4900,
//      y: 3610,
//      tx: 4825,
//      ty: 3700,
//      dx: -3,
//      direction1: "桑田岛",
//      startTime1: "6:37",
//      endTime1: "23:17",
//      direction2: "骑河",
//      startTime2: "6:00",
//      endTime2: "22:26",
//      type: "normal"
//  },
//  {
//      id: "0270",
//      name: "金谷路",
//      eName: "Jingu Lu",
//      x: 5115,
//      y: 3610,
//      tx: 5040,
//      ty: 3520,
//      dx: 15,
//      direction1: "桑田岛",
//      startTime1: "6:40",
//      endTime1: "23:20",
//      direction2: "骑河",
//      startTime2: "6:04",
//      endTime2: "22:24",
//      type: "normal"
//  },
//  {
//      id: "0271",
//      name: "金尚路",
//      eName: "Jinshang Lu",
//      x: 5316,
//      y: 3610,
//      tx: 5241,
//      ty: 3700,
//      dx: -5,
//      direction1: "桑田岛",
//      startTime1: "6:42",
//      endTime1: "23:22",
//      direction2: "骑河",
//      startTime2: "6:02",
//      endTime2: "22:22",
//      type: "normal"
//  },
//  {
//      id: "0272",
//      name: "桑田岛",
//      eName: "Sangtian Dao",
//      x: 5515,
//      y: 3610,
//      tx: 5440,
//      ty: 3700,
//      dx: -20,
//      direction1: "桑田岛",
//      startTime1: "—",
//      endTime1: "—",
//      direction2: "骑河",
//      startTime2: "6:00",
//      endTime2: "22:20",
//      type: "normal"
//  }
//);
//szmtr.line[7].station = new Array(
//  {
//      id: "0430",
//      name: "龙道浜",
//      eName: "Longdaobang",
//      x: 2525,
//      y: 385,
//      tx: 2315,
//      ty: 395,
//      dx: -50,
//      direction1: "同里",
//      startTime1: "6:00",
//      endTime1: "22:25",
//      direction2: "龙道浜",
//      startTime2: "—",
//      endTime2: "—",
//      type: "normal"
//  },
//  {
//      id: "0431",
//      name: "张庄",
//      eName: "Zhangzhuang",
//      x: 2525,
//      y: 605,
//      tx: 2365,
//      ty: 615,
//      dx: -97,
//      direction1: "同里",
//      startTime1: "6:02",
//      endTime1: "22:27",
//      direction2: "龙道浜",
//      startTime2: "6:33",
//      endTime2: "23:21",
//      type: "normal"
//  },
//  {
//      id: "0432",
//      name: "姚祥",
//      eName: "Yaoxiang",
//      x: 2525,
//      y: 830,
//      tx: 2365,
//      ty: 840,
//      dx: -40,
//      direction1: "同里",
//      startTime1: "6:03",
//      endTime1: "22:28",
//      direction2: "龙道浜",
//      startTime2: "6:31",
//      endTime2: "23:19",
//      type: "normal"
//  },
//  {
//      id: "0433",
//      name: "活力岛",
//      eName: "Huolidao",
//      x: 2525,
//      y: 1055,
//      tx: 2315,
//      ty: 1065,
//      dx: 13,
//      direction1: "同里",
//      startTime1: "6:06",
//      endTime1: "22:31",
//      direction2: "龙道浜",
//      startTime2: "6:29",
//      endTime2: "23:17",
//      type: "normal"
//  },
//  {
//      id: "0434",
//      name: "孙武纪念园",
//      eName: "Sunwu Jinianyuan",
//      x: 2525,
//      y: 1282,
//      tx: 2215,
//      ty: 1292,
//      dx: -8,
//      direction1: "同里",
//      startTime1: "6:00",
//      endTime1: "22:33",
//      direction2: "龙道浜",
//      startTime2: "6:27",
//      endTime2: "23:14",
//      type: "normal"
//  },
//  {
//      id: "0435",
//      name: "平泷路西",
//      eName: "Pinglonglu West",
//      x: 2525,
//      y: 1540,
//      tx: 2265,
//      ty: 1550,
//      dx: -40,
//      direction1: "同里",
//      startTime1: "6:02",
//      endTime1: "22:36",
//      direction2: "龙道浜",
//      startTime2: "6:24",
//      endTime2: "23:12",
//      type: "normal"
//  },
//  {id: "t0041", name: "过渡点", x: 2525, y: 1640, r: 45, sweep: 0, type: "temp"},
//  {
//      id: "0436",
//      name: "苏锦",
//      eName: "Sujin",
//      x: 2585,
//      y: 1700,
//      tx: 2425,
//      ty: 1710,
//      dx: 28,
//      direction1: "同里",
//      startTime1: "6:04",
//      endTime1: "22:38",
//      direction2: "龙道浜",
//      startTime2: "6:22",
//      endTime2: "23:10",
//      type: "normal"
//  },
//  {
//      id: "s2_0437",
//      name: "苏州火车站",
//      eName: "Suzhou Railway Station",
//      x: 2744,
//      y: 1858,
//      tx: 2814,
//      ty: 1864,
//      dx: 0,
//      direction1: "同里",
//      startTime1: "6:06",
//      endTime1: "22:40",
//      direction2: "龙道浜",
//      startTime2: "6:20",
//      endTime2: "23:08",
//      type: "transfer"
//  },
//  {
//      id: "0438",
//      name: "北寺塔",
//      eName: "Beisita",
//      x: 2880,
//      y: 1993,
//      tx: 2940,
//      ty: 1995,
//      dx: 0,
//      direction1: "同里",
//      startTime1: "6:09",
//      endTime1: "22:42",
//      direction2: "龙道浜",
//      startTime2: "6:17",
//      endTime2: "23:05",
//      type: "normal"
//  },
//  {id: "t0042", name: "过渡点", x: 2958, y: 2070, r: 45, sweep: 1, type: "temp"},
//  {
//      id: "0439",
//      name: "察院场",
//      eName: "Chayuanchang",
//      x: 2958,
//      y: 2190,
//      tx: 3018,
//      ty: 2180,
//      dx: 0,
//      direction1: "同里",
//      startTime1: "6:11",
//      endTime1: "22:44",
//      direction2: "龙道浜",
//      startTime2: "6:15",
//      endTime2: "23:03",
//      type: "normal"
//  },
//  {
//      id: "s3_0440",
//      name: "乐桥",
//      eName: "Leqiao",
//      x: 2958,
//      y: 2370,
//      tx: 2988,
//      ty: 2460,
//      dx: 5,
//      direction1: "同里",
//      startTime1: "6:00",
//      endTime1: "22:46",
//      direction2: "龙道浜",
//      startTime2: "6:14",
//      endTime2: "23:02",
//      type: "transfer"
//  },
//  {
//      id: "0441",
//      name: "三元坊",
//      eName: "Sanyuanfang",
//      x: 2958,
//      y: 2592,
//      tx: 3018,
//      ty: 2602,
//      dx: 0,
//      direction1: "同里",
//      startTime1: "6:01",
//      endTime1: "22:48",
//      direction2: "龙道浜",
//      startTime2: "6:12",
//      endTime2: "23:00",
//      type: "normal"
//  },
//  {
//      id: "0442",
//      name: "南门",
//      eName: "Nanmen",
//      x: 2958,
//      y: 2784,
//      tx: 3018,
//      ty: 2794,
//      dx: 0,
//      direction1: "同里",
//      startTime1: "6:03",
//      endTime1: "22:49",
//      direction2: "龙道浜",
//      startTime2: "6:10",
//      endTime2: "22:58",
//      type: "normal"
//  },
//  {
//      id: "0443",
//      name: "人民桥南",
//      eName: "Renminqiao South",
//      x: 2958,
//      y: 3002,
//      tx: 3018,
//      ty: 3012,
//      dx: 0,
//      direction1: "同里",
//      startTime1: "6:05",
//      endTime1: "22:51",
//      direction2: "龙道浜",
//      startTime2: "6:09",
//      endTime2: "22:57",
//      type: "normal"
//  },
//  {
//      id: "0444",
//      name: "团结桥",
//      eName: "Tuanjieqiao",
//      x: 2958,
//      y: 3165,
//      tx: 3018,
//      ty: 3175,
//      dx: 0,
//      direction1: "同里",
//      startTime1: "6:07",
//      endTime1: "22:53",
//      direction2: "龙道浜",
//      startTime2: "6:07",
//      endTime2: "22:55",
//      type: "normal"
//  },
//  {
//      id: "0445",
//      name: "宝带东路",
//      eName: "Baodai Lu",
//      x: 2958,
//      y: 3350,
//      tx: 3018,
//      ty: 3290,
//      dx: 0,
//      direction1: "同里",
//      startTime1: "6:00",
//      endTime1: "22:55",
//      direction2: "龙道浜",
//      startTime2: "6:05",
//      endTime2: "22:53",
//      type: "normal"
//  },
//  {
//      id: "s4_0446",
//      name: "石湖东路",
//      eName: "Shihu Donglu",
//      x: 2958,
//      y: 3610,
//      tx: 3008,
//      ty: 3530,
//      dx: 0,
//      direction1: "同里",
//      startTime1: "6:02",
//      endTime1: "22:58",
//      direction2: "龙道浜",
//      startTime2: "6:02",
//      endTime2: "22:50",
//      type: "transfer"
//  },
//  {
//      id: "s5_0447",
//      name: "红庄",
//      eName: "Hongzhuang",
//      x: 2958,
//      y: 3845,
//      tx: 3018,
//      ty: 3855,
//      dx: 0,
//      direction1: "同里",
//      startTime1: "6:05",
//      endTime1: "23:00",
//      direction2: "龙道浜",
//      startTime2: "6:00",
//      endTime2: "22:47",
//      type: "transfer"
//  },
//  {
//      id: "0448",
//      name: "淸树湾",
//      eName: "Qingshuwan",
//      x: 2958,
//      y: 4006,
//      tx: 3018,
//      ty: 4016,
//      dx: 0,
//      direction1: "同里",
//      startTime1: "6:07",
//      endTime1: "23:03",
//      direction2: "龙道浜",
//      startTime2: "6:08",
//      endTime2: "22:45",
//      type: "normal"
//  },
//  {
//      id: "0449",
//      name: "花港",
//      eName: "Huagang",
//      x: 2958,
//      y: 4152,
//      tx: 3018,
//      ty: 4162,
//      dx: 0,
//      direction1: "同里",
//      startTime1: "6:10",
//      endTime1: "23:06",
//      direction2: "龙道浜",
//      startTime2: "6:06",
//      endTime2: "22:42",
//      type: "normal"
//  },
//  {
//      id: "0450",
//      name: "江陵西路",
//      eName: "Jiangling Xilu",
//      x: 2958,
//      y: 4310,
//      tx: 3018,
//      ty: 4320,
//      dx: 0,
//      direction1: "同里",
//      startTime1: "6:14",
//      endTime1: "23:10",
//      direction2: "龙道浜",
//      startTime2: "6:02",
//      endTime2: "22:38",
//      type: "normal"
//  },
//  {id: "t0043", name: "过渡点", x: 2958, y: 4480, r: 45, sweep: 1, type: "temp"},
//  {
//      id: "0451",
//      name: "江兴西路",
//      eName: "Jiangxing Xilu",
//      x: 2800,
//      y: 4480,
//      tx: 2700,
//      ty: 4570,
//      dx: 0,
//      direction1: "同里",
//      startTime1: "6:16",
//      endTime1: "23:12",
//      direction2: "龙道浜",
//      startTime2: "6:00",
//      endTime2: "22:36",
//      type: "normal"
//  },
//  {
//      id: "0452",
//      name: "流虹路",
//      eName: "Liuhong Lu",
//      x: 2540,
//      y: 4480,
//      tx: 2465,
//      ty: 4390,
//      dx: -5,
//      direction1: "同里",
//      startTime1: "6:19",
//      endTime1: "23:15",
//      direction2: "龙道浜",
//      startTime2: "6:07",
//      endTime2: "22:33",
//      type: "normal"
//  },
//  {id: "t0044", name: "过渡点", x: 2332, y: 4480, r: 45, sweep: 0, type: "temp"},
//  {
//      id: "0453",
//      name: "笠泽路",
//      eName: "Lize Lu",
//      x: 2332,
//      y: 4616,
//      tx: 2122,
//      ty: 4626,
//      dx: +50,
//      direction1: "同里",
//      startTime1: "6:21",
//      endTime1: "23:16",
//      direction2: "龙道浜",
//      startTime2: "6:05",
//      endTime2: "22:31",
//      type: "normal"
//  },
//  {
//      id: "0454",
//      name: "顾家荡",
//      eName: "Gujiadang",
//      x: 2332,
//      y: 4838,
//      tx: 2122,
//      ty: 4848,
//      dx: 0,
//      direction1: "同里",
//      startTime1: "6:23",
//      endTime1: "23:18",
//      direction2: "龙道浜",
//      startTime2: "6:04",
//      endTime2: "22:29",
//      type: "normal"
//  },
//  {
//      id: "0455",
//      name: "苏州湾东",
//      eName: "Suzhouwan East",
//      x: 2332,
//      y: 5048,
//      tx: 2072,
//      ty: 5058,
//      dx: -35,
//      direction1: "同里",
//      startTime1: "6:25",
//      endTime1: "23:20",
//      direction2: "龙道浜",
//      startTime2: "6:02",
//      endTime2: "22:27",
//      type: "normal"
//  },
//  {id: "t0045", name: "过渡点", x: 2332, y: 5264, r: 45, sweep: 0, type: "temp"},
//  {
//      id: "0456",
//      name: "松陵大道",
//      eName: "Songling Dadao",
//      x: 2516,
//      y: 5264,
//      tx: 2416,
//      ty: 5174,
//      dx: -15,
//      direction1: "同里",
//      startTime1: "6:27",
//      endTime1: "23:22",
//      direction2: "龙道浜",
//      startTime2: "6:00",
//      endTime2: "22:25",
//      type: "normal"
//  },
//  {
//      id: "0457",
//      name: "吴江人民广场",
//      eName: "Wujiang Renmin Guangchang",
//      x: 2852,
//      y: 5264,
//      tx: 2702,
//      ty: 5354,
//      dx: -65,
//      direction1: "同里",
//      startTime1: "6:29",
//      endTime1: "23:25",
//      direction2: "龙道浜",
//      startTime2: "6:08",
//      endTime2: "22:23",
//      type: "normal"
//  },
//  {
//      id: "0458",
//      name: "吴江汽车站",
//      eName: "Wujiang Coach Station",
//      x: 3166,
//      y: 5264,
//      tx: 3041,
//      ty: 5174,
//      dx: -44,
//      direction1: "同里",
//      startTime1: "6:32",
//      endTime1: "23:28",
//      direction2: "龙道浜",
//      startTime2: "6:05",
//      endTime2: "22:20",
//      type: "normal"
//  },
//  {
//      id: "0459",
//      name: "庞金路",
//      eName: "Pangjin Lu",
//      x: 3528,
//      y: 5264,
//      tx: 3453,
//      ty: 5354,
//      dx: 0,
//      direction1: "同里",
//      startTime1: "6:35",
//      endTime1: "23:30",
//      direction2: "龙道浜",
//      startTime2: "6:02",
//      endTime2: "22:17",
//      type: "normal"
//  },
//  {
//      id: "0460",
//      name: "同里",
//      eName: "Tongli",
//      x: 3840,
//      y: 5264,
//      tx: 3790,
//      ty: 5174,
//      dx: 6,
//      direction1: "同里",
//      startTime1: "—",
//      endTime1: "—",
//      direction2: "龙道浜",
//      startTime2: "6:00",
//      endTime2: "22:15",
//      type: "normal"
//  }
//);
//szmtr.line[1].station = new Array(
//  {
//      id: "s5_0729",
//      name: "红庄",
//      eName: "Hongzhuang",
//      x: 2958,
//      y: 3845,
//      tx: 3018,
//      ty: 3855,
//      dx: 0,
//      direction1: "木里",
//      startTime1: "6:10",
//      endTime1: "22:35",
//      direction2: "红庄",
//      startTime2: "—",
//      endTime2: "—",
//      type: "transfer"
//  },
//  {
//      id: "0130",
//      name: " 蠡墅",
//      eName: "Lishu",
//      x: 2753,
//      y: 3845,
//      tx: 2703,
//      ty: 3935,
//      dx: 15,
//      direction1: "木里",
//      startTime1: "6:12",
//      endTime1: "22:37",
//      direction2: "红庄",
//      startTime2: "6:24",
//      endTime2: "22:28",
//      type: "normal"
//  },
//  {id: "t0011", name: "过渡点", x: 2640, y: 3845, r: 45, sweep: 0, type: "temp"},
//  {
//      id: "0731",
//      name: "石湖莫舍",
//      eName: "Shihu Moshe",
//      x: 2448,
//      y: 4032,
//      tx: 2468,
//      ty: 4112,
//      dx: 8,
//      direction1: "木里",
//      startTime1: "6:15",
//      endTime1: "22:40",
//      direction2: "红庄",
//      startTime2: "6:21",
//      endTime2: "22:26",
//      type: "normal"
//  },
//  {id: "t0012", name: "过渡点", x: 2250, y: 4225, r: 45, sweep: 1, type: "temp"},
//  {
//      id: "0132",
//      name: "越溪",
//      eName: "Yuexi",
//      x: 2200,
//      y: 4225,
//      tx: 2150,
//      ty: 4135,
//      dx: 10,
//      direction1: "木里",
//      startTime1: "6:17",
//      endTime1: "22:42",
//      direction2: "红庄",
//      startTime2: "6:19",
//      endTime2: "22:23",
//      type: "normal"
//  },
//  {
//      id: "0133",
//      name: "文溪路",
//      eName: "Wenxi Lu",
//      x: 1942,
//      y: 4225,
//      tx: 1867,
//      ty: 4315,
//      dx: 10,
//      direction1: "木里",
//      startTime1: "6:19",
//      endTime1: "22:44",
//      direction2: "红庄",
//      startTime2: "6:17",
//      endTime2: "22:21",
//      type: "normal"
//  },
//  {
//      id: "0134",
//      name: "天鹅荡路",
//      eName: "Tian'edang Lu",
//      x: 1650,
//      y: 4225,
//      tx: 1550,
//      ty: 4135,
//      dx: -1,
//      direction1: "木里",
//      startTime1: "6:22",
//      endTime1: "22:47",
//      direction2: "红庄",
//      startTime2: "6:14",
//      endTime2: "22:19",
//      type: "normal"
//  },
//  {
//      id: "0135",
//      name: "苏州湾北",
//      eName: "Suzhouwan North",
//      x: 1360,
//      y: 4225,
//      tx: 1260,
//      ty: 4315,
//      dx: -35,
//      direction1: "木里",
//      startTime1: "6:24",
//      endTime1: "22:49",
//      direction2: "红庄",
//      startTime2: "6:12",
//      endTime2: "22:17",
//      type: "normal"
//  },
//  {
//      id: "0136",
//      name: "木里",
//      eName: "Muli",
//      x: 1068,
//      y: 4225,
//      tx: 1018,
//      ty: 4135,
//      dx: 18,
//      direction1: "木里",
//      startTime1: "—",
//      endTime1: "—",
//      direction2: "红庄",
//      startTime2: "6:10",
//      endTime2: "22:15",
//      type: "normal"
//  }
//);
szmtr.line[0].station = new Array(
    {
        id: "0301",
        name: "竹岐",
//      eName: "zhuqi",
        x: 1228,
        y: 1064,
        tx: 1068,
        ty: 1084,
        dx: 5,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0302",
        name: "禧东",
//      eName: "禧东",
        x: 1228,
        y: 1214,
        tx: 1068,
        ty: 1234,
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0303",
        name: "春风",
//      eName: "chunfeng",
        x: 1228,
        y: 1364,
        tx: 1068,
        ty: 1384,
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0304",
        name: "苏洋",
//      eName: "",
        x: 1228,
        y: 1511,
        tx: 1068,
        ty: 1531,
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0305",
        name: "沙提",
//      eName: "Fazhan Lu",
        x: 1228,
        y: 1661,
        tx:1068,
        ty:1681,
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0306",
        name: "上街",
//      eName: "Wenchang Lu",
        x: 1228,
        y: 1811,
        tx:1068,
        ty:1831,
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0307",
        name: "金屿",
//      eName: "Lushan Lu",
        x: 1228,
        y: 1961,
        tx:1068,
        ty:1981,
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0308",
        name: "福州大学",
//      eName: "Huashan Lu",
        x: 1228,
        y: 2161,
        tx:968,
        ty:2191,
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0309",
        name: "董屿",
//      eName: "Heshan Lu",
        x: 1228,
        y: 2361,
        tx: 1068,
        ty: 2381,
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {id: "t0031", name: "过渡点", x: 1228, y: 2485, r: 45, sweep: 0, type: "temp"},
    {
        id: "0310",
        name: "厚庭",
//      eName: "Suzhou Amusement Land",
        x: 1378,
        y: 2485,
        tx: 1318,
        ty: 2575,
        dx: -60,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0311",
        name: "桔园州",
//      eName: "Suzhou Amusement Land",
        x: 1578,
        y: 2485,
        tx: 1478,
        ty: 2575,
        dx: -60,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0312",
        name: "洪湾",
//      eName: "Suzhou Amusement Land",
        x: 1798,
        y: 2485,
        tx: 1748,
        ty: 2575,
        dx: -60,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0313",
        name: "金山",
//      eName: "Suzhou Amusement Land",
        x: 1998,
        y: 2485,
        tx: 1948,
        ty: 2575, 
        dx: -60,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0314",
        name: "金祥",
//      eName: "Suzhou Amusement Land",
        x: 2168,
        y: 2485,
        tx: 2118,
        ty: 2575, 
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {id: "t0032", name: "过渡点", x: 2218, y: 2485, r: 45, sweep: 1, type: "temp"},
    {
        id: "0315",
        name: "祥坂",
//      eName: "Suzhou Amusement Land",
        x: 2348,
        y: 2355,
        tx: 2208,
        ty: 2365, 
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0316",
        name: "宁化",
//      eName: "Suzhou Amusement Land",
        x: 2498,
        y: 2205,
        tx: 2348,
        ty: 2215, 
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0317",
        name: "西洋",
//      eName: "Suzhou Amusement Land",
        x: 2648,
        y: 2055,
        tx: 2498,
        ty: 2065, 
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {id: "t0033", name: "过渡点", x: 2698, y: 2005, r: 45, sweep: 1, type: "temp"},
    {
        id: "0318",
        name: "南门兜",
//      eName: "Suzhou Amusement Land",
        x: 2848,
        y: 2005,
        tx: 2778,
        ty: 1945, 
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0319",
        name: "水部",
//      eName: "Suzhou Amusement Land",
        x: 3148,
        y: 2005,
        tx: 3098,
        ty: 1945, 
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0320",
        name: "紫阳",
//      eName: "Suzhou Amusement Land",
        x: 3348,
        y: 2005,
        tx: 3298,
        ty: 1945, 
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0321",
        name: "五里亭",
//      eName: "Suzhou Amusement Land",
        x: 3548,
        y: 2005,
        tx: 3478,
        ty: 1945, 
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0322",
        name: "前屿",
//      eName: "Suzhou Amusement Land",
        x: 3748,
        y: 2005,
        tx: 3698,
        ty: 1945, 
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {id: "t0034", name: "过渡点", x: 3758, y: 1965, r: 45, sweep: 1, type: "temp"},
    {
        id: "0323",
        name: "上洋",
//      eName: "Suzhou Amusement Land",
        x: 3948,
        y: 2155,
        tx: 3998,
        ty: 2175, 
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0324",
        name: "鼓山",
//      eName: "Suzhou Amusement Land",
        x: 4108,
        y: 2315,
        tx: 4158,
        ty: 2335, 
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0325",
        name: "洋里",
//      eName: "Suzhou Amusement Land",
        x: 4288,
        y: 2495,
        tx: 4338,
        ty: 2515, 
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0326",
        name: "",
//      eName: "Suzhou Amusement Land",
        x: 4488,
        y: 2695,
        tx: 4438,
        ty: 2695, 
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0327",
        name: "",
//      eName: "Suzhou Amusement Land",
        x: 4688,
        y: 2895,
        tx: 4688,
        ty: 2895, 
        dx: 0,
        direction1: "马尾区",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
);
//szmtr.line[1].station = new Array(
//  {
//      id: "0501",
//      name: "临时点",
//      eName: "",
//      x: 300,
//      y: 3047,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "normal"
//  },
//  {
//      id: "0502",
//      name: "临时点",
//      eName: "",
//      x: 1200,
//      y: 3047,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "normal"
//  },
//  {id: "t0051", name: "过渡点", x: 1316, y: 3047, r: 45, sweep: 0, type: "temp"},
//  {
//      id: "0503",
//      name: "临时点",
//      eName: "",
//      x: 1378,
//      y: 2982,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "normal"
//  },
//  {
//      id: "0504",
//      name: "临时点",
//      eName: "",
//      x: 1478,
//      y: 2882,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "normal"
//  },
//  {id: "t0052", name: "过渡点", x: 1568, y: 2785, r: 45, sweep: 1, type: "temp"},
//  {
//      id: "0505",
//      name: "临时点",
//      eName: "",
//      x: 1622,
//      y: 2785,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "normal"
//  },
//  {
//      id: "0506",
//      name: "临时点",
//      eName: "",
//      x: 5023,
//      y: 2785,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "normal"
//  },
//  {id: "t0053", name: "过渡点", x: 5085, y: 2785, r: 45, sweep: 0, type: "temp"},
//  {
//      id: "0507",
//      name: "临时点",
//      eName: "",
//      x: 5085,
//      y: 2731,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "normal"
//  },
//  {
//      id: "0508",
//      name: "临时点",
//      eName: "",
//      x: 5085,
//      y: 2053,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "normal"
//  },
//  {id: "t0054", name: "过渡点", x: 5085, y: 2009, r: 45, sweep: 1, type: "temp"},
//  {
//      id: "0509",
//      name: "临时点",
//      eName: "",
//      x: 5118,
//      y: 1976,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "normal"
//  },
//  {
//      id: "0510",
//      name: "临时点",
//      eName: "",
//      x: 5317,
//      y: 1776,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "normal"
//  },
//  {id: "t0055", name: "过渡点", x: 5345, y: 1748, r: 45, sweep: 0, type: "temp"},
//  {
//      id: "0511",
//      name: "临时点",
//      eName: "",
//      x: 5345,
//      y: 1710,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "normal"
//  },
//  {
//      id: "0512",
//      name: "临时点",
//      eName: "",
//      x: 5345,
//      y: 1431,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "normal"
//  }
//);
//szmtr.line[2].station = new Array(
//  {
//      id: "0601",
//      name: "临时点",
//      eName: "",
//      x: 1312,
//      y: 1030,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {
//      id: "0602",
//      name: "临时点",
//      eName: "",
//      x: 1927,
//      y: 1635,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {id: "t0061", name: "过渡点", x: 1993, y: 1700, r: 45, sweep: 0, type: "temp"},
//  {
//      id: "0603",
//      name: "临时点",
//      eName: "",
//      x: 2060,
//      y: 1700,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {
//      id: "0604",
//      name: "临时点",
//      eName: "",
//      x: 3100,
//      y: 1700,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {id: "t0062", name: "过渡点", x: 3225, y: 1700, r: 45, sweep: 1, type: "temp"},
//  {
//      id: "0605",
//      name: "临时点",
//      eName: "",
//      x: 3225,
//      y: 1800,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {
//      id: "0606",
//      name: "临时点",
//      eName: "",
//      x: 3225,
//      y: 2500,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {id: "t0063", name: "过渡点", x: 3225, y: 2580, r: 45, sweep: 0, type: "temp"},
//  {
//      id: "0607",
//      name: "临时点",
//      eName: "",
//      x: 3300,
//      y: 2580,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {
//      id: "0608",
//      name: "临时点",
//      eName: "",
//      x: 5200,
//      y: 2580,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {id: "t0064", name: "过渡点", x: 5309, y: 2580, r: 45, sweep: 1, type: "temp"},
//  {
//      id: "0609",
//      name: "临时点",
//      eName: "",
//      x: 5309,
//      y: 2700,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {
//      id: "0610",
//      name: "临时点",
//      eName: "",
//      x: 5309,
//      y: 3500,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {id: "t0065", name: "过渡点", x: 5309, y: 3560, r: 45, sweep: 0, type: "temp"},
//  {
//      id: "0611",
//      name: "临时点",
//      eName: "",
//      x: 5400,
//      y: 3560,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {
//      id: "0612",
//      name: "临时点",
//      eName: "",
//      x: 5515,
//      y: 3560,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  }
//);
//szmtr.line[3].station = new Array(
//  {
//      id: "0701",
//      name: "临时点",
//      eName: "",
//      x: 2800,
//      y: 520,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {
//      id: "0702",
//      name: "临时点",
//      eName: "",
//      x: 3600,
//      y: 520,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {id: "t0075", name: "过渡点", x: 3775, y: 520, r: 45, sweep: 1, type: "temp"},
//  {
//      id: "0703",
//      name: "临时点",
//      eName: "",
//      x: 3775,
//      y: 700,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {
//      id: "0704",
//      name: "临时点",
//      eName: "",
//      x: 3775,
//      y: 3500,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {id: "t0076", name: "过渡点", x: 3775, y: 3845, r: 45, sweep: 1, type: "temp"},
//  {
//      id: "0705",
//      name: "临时点",
//      eName: "",
//      x: 3500,
//      y: 3845,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {
//      id: "0706",
//      name: "临时点",
//      eName: "",
//      x: 2958,
//      y: 3845,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  }
//);
//szmtr.line[4].station = new Array(
//  {
//      id: "0801",
//      name: "临时点",
//      eName: "",
//      x: 1278,
//      y: 2133,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {
//      id: "0802",
//      name: "临时点",
//      eName: "",
//      x: 1278,
//      y: 1950,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {id: "t0081", name: "过渡点", x: 1278, y: 1857, r: 45, sweep: 1, type: "temp"},
//  {
//      id: "0803",
//      name: "临时点",
//      eName: "",
//      x: 1303,
//      y: 1832,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {
//      id: "0804",
//      name: "临时点",
//      eName: "",
//      x: 1780,
//      y: 1346,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {id: "t0082", name: "过渡点", x: 1844, y: 1282, r: 45, sweep: 1, type: "temp"},
//  {
//      id: "0805",
//      name: "临时点",
//      eName: "",
//      x: 1900,
//      y: 1282,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {
//      id: "0806",
//      name: "临时点",
//      eName: "",
//      x: 4000,
//      y: 1282,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {id: "t0083", name: "过渡点", x: 4152, y: 1282, r: 45, sweep: 1, type: "temp"},
//  {
//      id: "0807",
//      name: "临时点",
//      eName: "",
//      x: 4152,
//      y: 1380,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {
//      id: "0808",
//      name: "临时点",
//      eName: "",
//      x: 4152,
//      y: 1480,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {id: "t0084", name: "过渡点", x: 4152, y: 1570, r: 45, sweep: 0, type: "temp"},
//  {
//      id: "0809",
//      name: "临时点",
//      eName: "",
//      x: 4300,
//      y: 1570,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {
//      id: "0810",
//      name: "临时点",
//      eName: "",
//      x: 4400,
//      y: 1570,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {id: "t0085", name: "过渡点", x: 4528, y: 1570, r: 45, sweep: 1, type: "temp"},
//  {
//      id: "0811",
//      name: "临时点",
//      eName: "",
//      x: 4528,
//      y: 1700,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {
//      id: "0812",
//      name: "临时点",
//      eName: "",
//      x: 4528,
//      y: 2800,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {id: "t0086", name: "过渡点", x: 4528, y: 2978, r: 45, sweep: 0, type: "temp"},
//  {
//      id: "0813",
//      name: "临时点",
//      eName: "",
//      x: 4600,
//      y: 3050,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {
//      id: "0814",
//      name: "临时点",
//      eName: "",
//      x: 4790,
//      y: 3241,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {id: "t0087", name: "过渡点", x: 4900, y: 3352, r: 45, sweep: 1, type: "temp"},
//  {
//      id: "0815",
//      name: "临时点",
//      eName: "",
//      x: 4900,
//      y: 3500,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  },
//  {
//      id: "0816",
//      name: "临时点",
//      eName: "",
//      x: 4900,
//      y: 3970,
//      tx: 0,
//      ty: 0,
//      dx: 0,
//      direction1: "上行",
//      startTime1: "-",
//      endTime1: "-",
//      direction2: "下行",
//      startTime2: "—",
//      endTime2: "—",
//      type: "hide"
//  }
//);