var szmtr = {};
szmtr.lineNumber = 9;
szmtr.width = 5850;
szmtr.height = 5709;
szmtr.line = new Array();
szmtr.line[0] = {
    id: 3,
    name: "2号线",
    color: "#832c95",
    maskColor: "#d39dde",
    x1: 1100,
    y1: 1860,
	x2: 4140,
    y2: 3950,
    w: 210
};
szmtr.line[0].station = new Array(
    {
        id: "0301",
        name: "松北大学城站",
//      eName: "zhuqi",
        x: 1200,
        y: 2000,
        tx: 1260,
        ty: 2020,
        dx: 5,
        direction1: "气象台",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0302",
        name: "哈尔滨北站站",
        x: 1350,
        y: 2150,
        tx: 1410,
        ty: 2170,
        dx: 0,
        direction1: "气象台",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0303",
        name: "大耿家站",
//      eName: "chunfeng",
        x: 1500,
        y: 2300,
        tx: 1560,
        ty: 2320,
        dx: 0,
        direction1: "气象台",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0304",
        name: "龙川路站",
//      eName: "",
        x: 1650,
        y: 2450,
        tx: 1710,
        ty: 2470,
        dx: 0,
        direction1: "气象台",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {id: "t0031", name: "过渡点", x: 1620, y: 2480, r: 45, sweep: 0, type: "temp"},
//  {id: "t0032", name: "过渡点", x: 1560, y: 2540, r: 45, sweep: 0, type: "temp"},
    {
        id: "0305",
        name: "世茂大道站",
//      eName: "Fazhan Lu",
        x: 1560,
        y: 2650,
        tx:1580,
        ty:2670,
        dx: 0,
        direction1: "气象台",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {id: "t0032", name: "过渡点", x: 1560, y: 2800, r: 45, sweep: 0, type: "temp"},
    {
        id: "0306",
        name: "冰雪大世界站",
//      eName: "Wenchang Lu",
        x: 1700,
        y: 2900,
        tx:1760,
        ty:2920,
        dx: 0,
        direction1: "气象台",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
//  {id: "t0033", name: "过渡点", x: 1700, y: 2950, r: 45, sweep: 0, type: "temp"},
    {
        id: "0307",
        name: "太阳岛站",
//      eName: "Lushan Lu",
        x: 1980,
        y: 2850,
        tx:2040,
        ty:2865,
        dx: 0,
        direction1: "气象台",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0308",
        name: "人民广场站",
//      eName: "Huashan Lu",
        x: 2180,
        y: 3050,
        tx:2240,
        ty:3070,
        dx: 0,
        direction1: "气象台",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0309",
        name: "中央大街站",
//      eName: "Heshan Lu",
        x: 2380,
        y: 3250,
        tx: 2440,
        ty: 3270,
        dx: 0,
        direction1: "气象台",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    
    {
        id: "0310",
        name: "尚志大街站",
//      eName: "Suzhou Amusement Land",
        x: 2580,
        y: 3450,
        tx: 2450,
        ty: 3540,
        dx: -60,
        direction1: "气象台",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0311",
        name: "哈尔滨站站",
//      eName: "Suzhou Amusement Land",
        x: 2780,
        y: 3450,
        tx: 2680,
        ty: 3360,
        dx: -60,
        direction1: "气象台",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0312",
        name: "博物馆站",
//      eName: "Suzhou Amusement Land",
        x: 2980,
        y: 3450,
        tx: 2880,
        ty: 3540,
        dx: -60,
        direction1: "气象台",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0313",
        name: "工人文化宫站",
//      eName: "Suzhou Amusement Land",
        x: 3180,
        y: 3450,
        tx: 3020,
        ty: 3360,
        dx: -60,
        direction1: "气象台",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0314",
        name: "省政府站",
//      eName: "Suzhou Amusement Land",
        x: 3380,
        y: 3450,
        tx: 3280,
        ty: 3540,
        dx: -60,
        direction1: "气象台",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0315",
        name: "衡山路站",
//      eName: "Suzhou Amusement Land",
       	x: 3580,
        y: 3450,
        tx: 3420,
        ty: 3360,
        dx: -60,
        direction1: "气象台",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0316",
        name: "珠江路站",
//      eName: "Suzhou Amusement Land",
        x: 3780,
        y: 3450,
        tx: 3680,
        ty: 3360,
        dx: -60,
        direction1: "气象台",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0317",
        name: "南直路站",
//      eName: "Suzhou Amusement Land",
        x: 3940,
        y: 3600,
        tx: 4000,
        ty: 3615, 
        dx: 0,
        direction1: "气象台",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0318",
        name: "东北农业大学站",
//      eName: "Suzhou Amusement Land",
        x: 4090,
        y: 3750,
        tx: 4150,
        ty: 3765,  
        dx: 0,
        direction1: "气象台",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
    {
        id: "0319",
        name: "气象台站",
//      eName: "Suzhou Amusement Land",
       	x: 4240,
        y: 3900,
        tx: 4300,
        ty: 3915,  
        dx: 0,
        direction1: "气象台",
        startTime1: "-",
        endTime1: "-",
        direction2: "下行",
        startTime2: "—",
        endTime2: "—",
        type: "normal"
    },
);
